# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from definitions/IkaSensorStamp.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class IkaSensorStamp(genpy.Message):
  _md5sum = "cdf180a59968af80fb045f033c5dfbcf"
  _type = "definitions/IkaSensorStamp"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 IdSensor                 # Source ID of the measuring sensor (see enums)
uint16 IdObjectWithinSensor     # IdInternal of the measured object within the sensor's object list
time measuredStamp              # ROS time stamp of when the sensor measured the object

#for enum types see definitions/utility/object_definitions.h
"""
  __slots__ = ['IdSensor','IdObjectWithinSensor','measuredStamp']
  _slot_types = ['uint16','uint16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       IdSensor,IdObjectWithinSensor,measuredStamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IkaSensorStamp, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.IdSensor is None:
        self.IdSensor = 0
      if self.IdObjectWithinSensor is None:
        self.IdObjectWithinSensor = 0
      if self.measuredStamp is None:
        self.measuredStamp = genpy.Time()
    else:
      self.IdSensor = 0
      self.IdObjectWithinSensor = 0
      self.measuredStamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H2I().pack(_x.IdSensor, _x.IdObjectWithinSensor, _x.measuredStamp.secs, _x.measuredStamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.measuredStamp is None:
        self.measuredStamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.IdSensor, _x.IdObjectWithinSensor, _x.measuredStamp.secs, _x.measuredStamp.nsecs,) = _get_struct_2H2I().unpack(str[start:end])
      self.measuredStamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H2I().pack(_x.IdSensor, _x.IdObjectWithinSensor, _x.measuredStamp.secs, _x.measuredStamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.measuredStamp is None:
        self.measuredStamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.IdSensor, _x.IdObjectWithinSensor, _x.measuredStamp.secs, _x.measuredStamp.nsecs,) = _get_struct_2H2I().unpack(str[start:end])
      self.measuredStamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H2I = None
def _get_struct_2H2I():
    global _struct_2H2I
    if _struct_2H2I is None:
        _struct_2H2I = struct.Struct("<2H2I")
    return _struct_2H2I
