# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from definitions/IkaEgoMotion.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class IkaEgoMotion(genpy.Message):
  _md5sum = "e0618c9f9aa211f416eed80f5aa9a953"
  _type = "definitions/IkaEgoMotion"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

#Vehicle motion variables
float32 fSteeringAngle                #[rad] Single-Track_Steering-Angle         
float32 fSteeringAngleRate            ##[deg/s]                                   
float32 fVelocity                     #[m/s] Velocity mean, signed               
float32 fVelocityFR                   #[m/s] Velocity FR, signed                 
float32 fVelocityFL                   #[m/s] Velocity FL, signed                 
float32 fVelocityRR                   #[m/s] Velocity RR, signed                 
float32 fVelocityRL                   #[m/s] Velocity RL, signed                 
float32 fAccelerationLateral          #[m/s^2]                                    
float32 fAccelerationLongitudinal     #[m/s^2]                                    
float32 fYawRate                      #[rad/s]                                   
float32 fPitch                        #[%]                                      
float32 fTrackCurvature               #[1/m]                                     
float32 nMovingDir                    #0: Standing, 1: Forward, -1 Backward
bool bStandStill

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','fSteeringAngle','fSteeringAngleRate','fVelocity','fVelocityFR','fVelocityFL','fVelocityRR','fVelocityRL','fAccelerationLateral','fAccelerationLongitudinal','fYawRate','fPitch','fTrackCurvature','nMovingDir','bStandStill']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,fSteeringAngle,fSteeringAngleRate,fVelocity,fVelocityFR,fVelocityFL,fVelocityRR,fVelocityRL,fAccelerationLateral,fAccelerationLongitudinal,fYawRate,fPitch,fTrackCurvature,nMovingDir,bStandStill

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IkaEgoMotion, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.fSteeringAngle is None:
        self.fSteeringAngle = 0.
      if self.fSteeringAngleRate is None:
        self.fSteeringAngleRate = 0.
      if self.fVelocity is None:
        self.fVelocity = 0.
      if self.fVelocityFR is None:
        self.fVelocityFR = 0.
      if self.fVelocityFL is None:
        self.fVelocityFL = 0.
      if self.fVelocityRR is None:
        self.fVelocityRR = 0.
      if self.fVelocityRL is None:
        self.fVelocityRL = 0.
      if self.fAccelerationLateral is None:
        self.fAccelerationLateral = 0.
      if self.fAccelerationLongitudinal is None:
        self.fAccelerationLongitudinal = 0.
      if self.fYawRate is None:
        self.fYawRate = 0.
      if self.fPitch is None:
        self.fPitch = 0.
      if self.fTrackCurvature is None:
        self.fTrackCurvature = 0.
      if self.nMovingDir is None:
        self.nMovingDir = 0.
      if self.bStandStill is None:
        self.bStandStill = False
    else:
      self.header = std_msgs.msg.Header()
      self.fSteeringAngle = 0.
      self.fSteeringAngleRate = 0.
      self.fVelocity = 0.
      self.fVelocityFR = 0.
      self.fVelocityFL = 0.
      self.fVelocityRR = 0.
      self.fVelocityRL = 0.
      self.fAccelerationLateral = 0.
      self.fAccelerationLongitudinal = 0.
      self.fYawRate = 0.
      self.fPitch = 0.
      self.fTrackCurvature = 0.
      self.nMovingDir = 0.
      self.bStandStill = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13fB().pack(_x.fSteeringAngle, _x.fSteeringAngleRate, _x.fVelocity, _x.fVelocityFR, _x.fVelocityFL, _x.fVelocityRR, _x.fVelocityRL, _x.fAccelerationLateral, _x.fAccelerationLongitudinal, _x.fYawRate, _x.fPitch, _x.fTrackCurvature, _x.nMovingDir, _x.bStandStill))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 53
      (_x.fSteeringAngle, _x.fSteeringAngleRate, _x.fVelocity, _x.fVelocityFR, _x.fVelocityFL, _x.fVelocityRR, _x.fVelocityRL, _x.fAccelerationLateral, _x.fAccelerationLongitudinal, _x.fYawRate, _x.fPitch, _x.fTrackCurvature, _x.nMovingDir, _x.bStandStill,) = _get_struct_13fB().unpack(str[start:end])
      self.bStandStill = bool(self.bStandStill)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13fB().pack(_x.fSteeringAngle, _x.fSteeringAngleRate, _x.fVelocity, _x.fVelocityFR, _x.fVelocityFL, _x.fVelocityRR, _x.fVelocityRL, _x.fAccelerationLateral, _x.fAccelerationLongitudinal, _x.fYawRate, _x.fPitch, _x.fTrackCurvature, _x.nMovingDir, _x.bStandStill))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 53
      (_x.fSteeringAngle, _x.fSteeringAngleRate, _x.fVelocity, _x.fVelocityFR, _x.fVelocityFL, _x.fVelocityRR, _x.fVelocityRL, _x.fAccelerationLateral, _x.fAccelerationLongitudinal, _x.fYawRate, _x.fPitch, _x.fTrackCurvature, _x.nMovingDir, _x.bStandStill,) = _get_struct_13fB().unpack(str[start:end])
      self.bStandStill = bool(self.bStandStill)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13fB = None
def _get_struct_13fB():
    global _struct_13fB
    if _struct_13fB is None:
        _struct_13fB = struct.Struct("<13fB")
    return _struct_13fB
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
