# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from definitions/v2x_CAM_protectedCommunicationZone.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class v2x_CAM_protectedCommunicationZone(genpy.Message):
  _md5sum = "837bc86ce87e38594fea352e22b6ddba"
  _type = "definitions/v2x_CAM_protectedCommunicationZone"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8    protectedZoneType
bool expiryTimePresent
uint64    expiryTime
int32    protectedZoneLatitude
int32    protectedZoneLongitude
bool protectedZoneRadiusPresent
uint8    protectedZoneRadius
uint32    protectedZoneID
bool protectedZoneIDPresent
"""
  __slots__ = ['protectedZoneType','expiryTimePresent','expiryTime','protectedZoneLatitude','protectedZoneLongitude','protectedZoneRadiusPresent','protectedZoneRadius','protectedZoneID','protectedZoneIDPresent']
  _slot_types = ['uint8','bool','uint64','int32','int32','bool','uint8','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       protectedZoneType,expiryTimePresent,expiryTime,protectedZoneLatitude,protectedZoneLongitude,protectedZoneRadiusPresent,protectedZoneRadius,protectedZoneID,protectedZoneIDPresent

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(v2x_CAM_protectedCommunicationZone, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.protectedZoneType is None:
        self.protectedZoneType = 0
      if self.expiryTimePresent is None:
        self.expiryTimePresent = False
      if self.expiryTime is None:
        self.expiryTime = 0
      if self.protectedZoneLatitude is None:
        self.protectedZoneLatitude = 0
      if self.protectedZoneLongitude is None:
        self.protectedZoneLongitude = 0
      if self.protectedZoneRadiusPresent is None:
        self.protectedZoneRadiusPresent = False
      if self.protectedZoneRadius is None:
        self.protectedZoneRadius = 0
      if self.protectedZoneID is None:
        self.protectedZoneID = 0
      if self.protectedZoneIDPresent is None:
        self.protectedZoneIDPresent = False
    else:
      self.protectedZoneType = 0
      self.expiryTimePresent = False
      self.expiryTime = 0
      self.protectedZoneLatitude = 0
      self.protectedZoneLongitude = 0
      self.protectedZoneRadiusPresent = False
      self.protectedZoneRadius = 0
      self.protectedZoneID = 0
      self.protectedZoneIDPresent = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2BQ2i2BIB().pack(_x.protectedZoneType, _x.expiryTimePresent, _x.expiryTime, _x.protectedZoneLatitude, _x.protectedZoneLongitude, _x.protectedZoneRadiusPresent, _x.protectedZoneRadius, _x.protectedZoneID, _x.protectedZoneIDPresent))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.protectedZoneType, _x.expiryTimePresent, _x.expiryTime, _x.protectedZoneLatitude, _x.protectedZoneLongitude, _x.protectedZoneRadiusPresent, _x.protectedZoneRadius, _x.protectedZoneID, _x.protectedZoneIDPresent,) = _get_struct_2BQ2i2BIB().unpack(str[start:end])
      self.expiryTimePresent = bool(self.expiryTimePresent)
      self.protectedZoneRadiusPresent = bool(self.protectedZoneRadiusPresent)
      self.protectedZoneIDPresent = bool(self.protectedZoneIDPresent)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2BQ2i2BIB().pack(_x.protectedZoneType, _x.expiryTimePresent, _x.expiryTime, _x.protectedZoneLatitude, _x.protectedZoneLongitude, _x.protectedZoneRadiusPresent, _x.protectedZoneRadius, _x.protectedZoneID, _x.protectedZoneIDPresent))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.protectedZoneType, _x.expiryTimePresent, _x.expiryTime, _x.protectedZoneLatitude, _x.protectedZoneLongitude, _x.protectedZoneRadiusPresent, _x.protectedZoneRadius, _x.protectedZoneID, _x.protectedZoneIDPresent,) = _get_struct_2BQ2i2BIB().unpack(str[start:end])
      self.expiryTimePresent = bool(self.expiryTimePresent)
      self.protectedZoneRadiusPresent = bool(self.protectedZoneRadiusPresent)
      self.protectedZoneIDPresent = bool(self.protectedZoneIDPresent)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BQ2i2BIB = None
def _get_struct_2BQ2i2BIB():
    global _struct_2BQ2i2BIB
    if _struct_2BQ2i2BIB is None:
        _struct_2BQ2i2BIB = struct.Struct("<2BQ2i2BIB")
    return _struct_2BQ2i2BIB
