# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from definitions/v2x_MAP.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import definitions.msg
import geometry_msgs.msg
import std_msgs.msg

class v2x_MAP(genpy.Message):
  _md5sum = "2d4ab11f239542c98de4ee314e01377a"
  _type = "definitions/v2x_MAP"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#Conversion of MAP intersections with adjacent lanes to lanelet map format 
v2x_MAP_Intersection[] intersections
int32[] layerIDs
================================================================================
MSG: definitions/v2x_MAP_Intersection
#header
Header header

# intersectionReferenceId
int32 id

# refPoint of Intersection in local coordinate system generated by ll2 projector
float32 refPoint_x
float32 refPoint_y
float32 refPoint_z

# area that is covered by lanes (relevant for extracting submap from ll2 map)
float32 maxPointX
float32 maxPointY
float32 minPointX
float32 minPointY


#Information of the different adjacent lanes
v2x_MAP_Lane[] adjacent_lanes


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: definitions/v2x_MAP_Lane
#enum directionalUse
uint8 LaneDirection_ingressPath = 0
uint8 LaneDirection_egressPath = 1
###############################################################

#general laneInformation 
    uint8 laneId
    uint8 directionalUse
    uint8 laneType  # Values as defined in SAE J 2735, "LaneTypeAttributes"
                    # 0: Vehicle, 2: Bike Lane

#coordinates of lane as flat earth projection from refPoint
    geometry_msgs/Point[] lane_coordinates

#list of lane connections
    v2x_MAP_Connection[] connections

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: definitions/v2x_MAP_Connection
#Connection
    #ConnectingLane
    uint8 connectingLane_laneId
    uint16 intersectionId #optional
    bool signalGroupId_present
    uint8 signalGroupId #optional
"""
  __slots__ = ['intersections','layerIDs']
  _slot_types = ['definitions/v2x_MAP_Intersection[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       intersections,layerIDs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(v2x_MAP, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.intersections is None:
        self.intersections = []
      if self.layerIDs is None:
        self.layerIDs = []
    else:
      self.intersections = []
      self.layerIDs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.intersections)
      buff.write(_struct_I.pack(length))
      for val1 in self.intersections:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_i7f().pack(_x.id, _x.refPoint_x, _x.refPoint_y, _x.refPoint_z, _x.maxPointX, _x.maxPointY, _x.minPointX, _x.minPointY))
        length = len(val1.adjacent_lanes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.adjacent_lanes:
          _x = val2
          buff.write(_get_struct_3B().pack(_x.laneId, _x.directionalUse, _x.laneType))
          length = len(val2.lane_coordinates)
          buff.write(_struct_I.pack(length))
          for val3 in val2.lane_coordinates:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          length = len(val2.connections)
          buff.write(_struct_I.pack(length))
          for val3 in val2.connections:
            _x = val3
            buff.write(_get_struct_BH2B().pack(_x.connectingLane_laneId, _x.intersectionId, _x.signalGroupId_present, _x.signalGroupId))
      length = len(self.layerIDs)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.layerIDs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.intersections is None:
        self.intersections = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.intersections = []
      for i in range(0, length):
        val1 = definitions.msg.v2x_MAP_Intersection()
        _v3 = val1.header
        start = end
        end += 4
        (_v3.seq,) = _get_struct_I().unpack(str[start:end])
        _v4 = _v3.stamp
        _x = _v4
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v3.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v3.frame_id = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.id, _x.refPoint_x, _x.refPoint_y, _x.refPoint_z, _x.maxPointX, _x.maxPointY, _x.minPointX, _x.minPointY,) = _get_struct_i7f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.adjacent_lanes = []
        for i in range(0, length):
          val2 = definitions.msg.v2x_MAP_Lane()
          _x = val2
          start = end
          end += 3
          (_x.laneId, _x.directionalUse, _x.laneType,) = _get_struct_3B().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.lane_coordinates = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.lane_coordinates.append(val3)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.connections = []
          for i in range(0, length):
            val3 = definitions.msg.v2x_MAP_Connection()
            _x = val3
            start = end
            end += 5
            (_x.connectingLane_laneId, _x.intersectionId, _x.signalGroupId_present, _x.signalGroupId,) = _get_struct_BH2B().unpack(str[start:end])
            val3.signalGroupId_present = bool(val3.signalGroupId_present)
            val2.connections.append(val3)
          val1.adjacent_lanes.append(val2)
        self.intersections.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.layerIDs = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.intersections)
      buff.write(_struct_I.pack(length))
      for val1 in self.intersections:
        _v5 = val1.header
        _x = _v5.seq
        buff.write(_get_struct_I().pack(_x))
        _v6 = _v5.stamp
        _x = _v6
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v5.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_i7f().pack(_x.id, _x.refPoint_x, _x.refPoint_y, _x.refPoint_z, _x.maxPointX, _x.maxPointY, _x.minPointX, _x.minPointY))
        length = len(val1.adjacent_lanes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.adjacent_lanes:
          _x = val2
          buff.write(_get_struct_3B().pack(_x.laneId, _x.directionalUse, _x.laneType))
          length = len(val2.lane_coordinates)
          buff.write(_struct_I.pack(length))
          for val3 in val2.lane_coordinates:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          length = len(val2.connections)
          buff.write(_struct_I.pack(length))
          for val3 in val2.connections:
            _x = val3
            buff.write(_get_struct_BH2B().pack(_x.connectingLane_laneId, _x.intersectionId, _x.signalGroupId_present, _x.signalGroupId))
      length = len(self.layerIDs)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.layerIDs.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.intersections is None:
        self.intersections = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.intersections = []
      for i in range(0, length):
        val1 = definitions.msg.v2x_MAP_Intersection()
        _v7 = val1.header
        start = end
        end += 4
        (_v7.seq,) = _get_struct_I().unpack(str[start:end])
        _v8 = _v7.stamp
        _x = _v8
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v7.frame_id = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.id, _x.refPoint_x, _x.refPoint_y, _x.refPoint_z, _x.maxPointX, _x.maxPointY, _x.minPointX, _x.minPointY,) = _get_struct_i7f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.adjacent_lanes = []
        for i in range(0, length):
          val2 = definitions.msg.v2x_MAP_Lane()
          _x = val2
          start = end
          end += 3
          (_x.laneId, _x.directionalUse, _x.laneType,) = _get_struct_3B().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.lane_coordinates = []
          for i in range(0, length):
            val3 = geometry_msgs.msg.Point()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.lane_coordinates.append(val3)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.connections = []
          for i in range(0, length):
            val3 = definitions.msg.v2x_MAP_Connection()
            _x = val3
            start = end
            end += 5
            (_x.connectingLane_laneId, _x.intersectionId, _x.signalGroupId_present, _x.signalGroupId,) = _get_struct_BH2B().unpack(str[start:end])
            val3.signalGroupId_present = bool(val3.signalGroupId_present)
            val2.connections.append(val3)
          val1.adjacent_lanes.append(val2)
        self.intersections.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.layerIDs = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_BH2B = None
def _get_struct_BH2B():
    global _struct_BH2B
    if _struct_BH2B is None:
        _struct_BH2B = struct.Struct("<BH2B")
    return _struct_BH2B
_struct_i7f = None
def _get_struct_i7f():
    global _struct_i7f
    if _struct_i7f is None:
        _struct_i7f = struct.Struct("<i7f")
    return _struct_i7f
