// Generated by gencpp from file definitions/FlatlandVehicleState.msg
// DO NOT EDIT!


#ifndef DEFINITIONS_MESSAGE_FLATLANDVEHICLESTATE_H
#define DEFINITIONS_MESSAGE_FLATLANDVEHICLESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace definitions
{
template <class ContainerAllocator>
struct FlatlandVehicleState_
{
  typedef FlatlandVehicleState_<ContainerAllocator> Type;

  FlatlandVehicleState_()
    : header()
    , velocity(0.0)
    , acceleration(0.0)
    , yaw_rate(0.0)
    , steering_angle(0.0)  {
    }
  FlatlandVehicleState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(0.0)
    , acceleration(0.0)
    , yaw_rate(0.0)
    , steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::definitions::FlatlandVehicleState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::definitions::FlatlandVehicleState_<ContainerAllocator> const> ConstPtr;

}; // struct FlatlandVehicleState_

typedef ::definitions::FlatlandVehicleState_<std::allocator<void> > FlatlandVehicleState;

typedef boost::shared_ptr< ::definitions::FlatlandVehicleState > FlatlandVehicleStatePtr;
typedef boost::shared_ptr< ::definitions::FlatlandVehicleState const> FlatlandVehicleStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::definitions::FlatlandVehicleState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::definitions::FlatlandVehicleState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::definitions::FlatlandVehicleState_<ContainerAllocator1> & lhs, const ::definitions::FlatlandVehicleState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::definitions::FlatlandVehicleState_<ContainerAllocator1> & lhs, const ::definitions::FlatlandVehicleState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace definitions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::definitions::FlatlandVehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::definitions::FlatlandVehicleState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::definitions::FlatlandVehicleState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04f370802b9205d70f005fd0c93bab98";
  }

  static const char* value(const ::definitions::FlatlandVehicleState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04f370802b9205d7ULL;
  static const uint64_t static_value2 = 0x0f005fd0c93bab98ULL;
};

template<class ContainerAllocator>
struct DataType< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "definitions/FlatlandVehicleState";
  }

  static const char* value(const ::definitions::FlatlandVehicleState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Simulated vehicle state\n"
"float32 velocity        # Current velocity of the vehicle\n"
"float32 acceleration    # Target Acceleration of the vehicle\n"
"float32 yaw_rate        # Current yaw rate of the vehicle\n"
"float32 steering_angle  # Target steering angle of the vehicle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::definitions::FlatlandVehicleState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.yaw_rate);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlatlandVehicleState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::definitions::FlatlandVehicleState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::definitions::FlatlandVehicleState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEFINITIONS_MESSAGE_FLATLANDVEHICLESTATE_H
