// Generated by gencpp from file definitions/v2x_SPAT_VehicleToLanePosition.msg
// DO NOT EDIT!


#ifndef DEFINITIONS_MESSAGE_V2X_SPAT_VEHICLETOLANEPOSITION_H
#define DEFINITIONS_MESSAGE_V2X_SPAT_VEHICLETOLANEPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace definitions
{
template <class ContainerAllocator>
struct v2x_SPAT_VehicleToLanePosition_
{
  typedef v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> Type;

  v2x_SPAT_VehicleToLanePosition_()
    : stationID(0)
    , laneID(0)  {
    }
  v2x_SPAT_VehicleToLanePosition_(const ContainerAllocator& _alloc)
    : stationID(0)
    , laneID(0)  {
  (void)_alloc;
    }



   typedef uint32_t _stationID_type;
  _stationID_type stationID;

   typedef uint8_t _laneID_type;
  _laneID_type laneID;





  typedef boost::shared_ptr< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> const> ConstPtr;

}; // struct v2x_SPAT_VehicleToLanePosition_

typedef ::definitions::v2x_SPAT_VehicleToLanePosition_<std::allocator<void> > v2x_SPAT_VehicleToLanePosition;

typedef boost::shared_ptr< ::definitions::v2x_SPAT_VehicleToLanePosition > v2x_SPAT_VehicleToLanePositionPtr;
typedef boost::shared_ptr< ::definitions::v2x_SPAT_VehicleToLanePosition const> v2x_SPAT_VehicleToLanePositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator1> & lhs, const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator2> & rhs)
{
  return lhs.stationID == rhs.stationID &&
    lhs.laneID == rhs.laneID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator1> & lhs, const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace definitions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ded075438e715a7244b92d3e851af87d";
  }

  static const char* value(const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xded075438e715a72ULL;
  static const uint64_t static_value2 = 0x44b92d3e851af87dULL;
};

template<class ContainerAllocator>
struct DataType< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "definitions/v2x_SPAT_VehicleToLanePosition";
  }

  static const char* value(const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 stationID\n"
"uint8 laneID\n"
;
  }

  static const char* value(const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stationID);
      stream.next(m.laneID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct v2x_SPAT_VehicleToLanePosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::definitions::v2x_SPAT_VehicleToLanePosition_<ContainerAllocator>& v)
  {
    s << indent << "stationID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stationID);
    s << indent << "laneID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.laneID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEFINITIONS_MESSAGE_V2X_SPAT_VEHICLETOLANEPOSITION_H
