(cl:in-package definitions-msg)
(cl:export '(TIME-VAL
          TIME
          X-VAL
          X
          Y-VAL
          Y
          THETA-VAL
          THETA
          V-VAL
          V
          A-VAL
          A
          KAPPA-VAL
          KAPPA
          DKAPPA-VAL
          DKAPPA
          S-VAL
          S
          TIMESTAMP-VAL
          TIMESTAMP
          VALID-VAL
          VALID
          NUM_ELEMENTS-VAL
          NUM_ELEMENTS
          SAMPLING_MODE-VAL
          SAMPLING_MODE
          ACTIVATIONMODELATERAL-VAL
          ACTIVATIONMODELATERAL
          ACTIVATIONMODELONGITUDINAL-VAL
          ACTIVATIONMODELONGITUDINAL
))