(cl:in-package definitions-msg)
(cl:export '(HEADER_PROTOCOLVERSION-VAL
          HEADER_PROTOCOLVERSION
          HEADER_MESSAGEID-VAL
          HEADER_MESSAGEID
          HEADER_STATIONID-VAL
          HEADER_STATIONID
          SPATDATA_MSGID-VAL
          SPATDATA_MSGID
          SPATDATA_MSGSUBID-VAL
          SPATDATA_MSGSUBID
          SPATDATA_MSGSUBID_PRESENT-VAL
          SPATDATA_MSGSUBID_PRESENT
          SPATDATA_NAME-VAL
          SPATDATA_NAME
          SPATDATA_NAME_PRESENT-VAL
          SPATDATA_NAME_PRESENT
          SPATDATA_INTERSECTIONS-VAL
          SPATDATA_INTERSECTIONS
          SPATDATA_REGIONAL_PRESENT-VAL
          SPATDATA_REGIONAL_PRESENT
))