(cl:in-package definitions-msg)
(cl:export '(STATIONTYPE-VAL
          STATIONTYPE
          REFERENCEPOSITION_LATITUDE-VAL
          REFERENCEPOSITION_LATITUDE
          REFERENCEPOSITION_LONGITUDE-VAL
          REFERENCEPOSITION_LONGITUDE
          REFERENCEPOSITION_POSITIONCONFIDENCEELLIPSE_SEMIMAJORCONFIDENCE-VAL
          REFERENCEPOSITION_POSITIONCONFIDENCEELLIPSE_SEMIMAJORCONFIDENCE
          REFERENCEPOSITION_POSITIONCONFIDENCEELLIPSE_SEMIMINORCONFIDENCE-VAL
          REFERENCEPOSITION_POSITIONCONFIDENCEELLIPSE_SEMIMINORCONFIDENCE
          REFERENCEPOSITION_POSITIONCONFIDENCEELLIPSE_SEMIMAJORORIENTATIONHEADINGVALUE-VAL
          REFERENCEPOSITION_POSITIONCONFIDENCEELLIPSE_SEMIMAJORORIENTATIONHEADINGVALUE
          REFERENCEPOSITION_ALTITUDE_ALTITUDEVALUE-VAL
          REFERENCEPOSITION_ALTITUDE_ALTITUDEVALUE
          REFERENCEPOSITION_ALTITUDE_ALTITUDECONFIDENCE-VAL
          REFERENCEPOSITION_ALTITUDE_ALTITUDECONFIDENCE
))