(cl:in-package definitions-msg)
(cl:export '(NAME-VAL
          NAME
          NAME_PRESENT-VAL
          NAME_PRESENT
          ID_REGION-VAL
          ID_REGION
          ID_REGION_PRESENT-VAL
          ID_REGION_PRESENT
          ID_ID-VAL
          ID_ID
          REVISION-VAL
          REVISION
          STATUS-VAL
          STATUS
          MOY-VAL
          MOY
          MOY_PRESENT-VAL
          MOY_PRESENT
          TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_PRESENT-VAL
          TIMESTAMP_PRESENT
          ENABLEDLANES-VAL
          ENABLEDLANES
          ENABLEDLANES_PRESENT-VAL
          ENABLEDLANES_PRESENT
          STATES-VAL
          STATES
          MANEUVERASSISTLIST-VAL
          MANEUVERASSISTLIST
          MANEUVERASSISTLIST_PRESENT-VAL
          MANEUVERASSISTLIST_PRESENT
          PRIORITY-VAL
          PRIORITY
          PRIORITY_PRESENT-VAL
          PRIORITY_PRESENT
          PREEMPT-VAL
          PREEMPT
          PREEMPT_PRESENT-VAL
          PREEMPT_PRESENT
          REGIONAL-VAL
          REGIONAL
          REGIONAL_PRESENT-VAL
          REGIONAL_PRESENT
))