(cl:in-package definitions-msg)
(cl:export '(HEADER-VAL
          HEADER
          IDMOTIONMODEL-VAL
          IDMOTIONMODEL
          FMEAN-VAL
          FMEAN
          FCOVARIANCE-VAL
          FCOVARIANCE
          FRELVELX-VAL
          FRELVELX
          FRELVELY-VAL
          FRELVELY
          FRELACCX-VAL
          FRELACCX
          FRELACCY-VAL
          FRELACCY
          REFLOCATION-VAL
          REFLOCATION
          FREFX-VAL
          FREFX
          FREFY-VAL
          FREFY
          IDINTERNAL-VAL
          IDINTERNAL
          IDLANE-VAL
          IDLANE
          IDTYPE-VAL
          IDTYPE
          FCLASSPROBABILITY-VAL
          FCLASSPROBABILITY
          FEXISTENCEPROBABILITY-VAL
          FEXISTENCEPROBABILITY
          IDEXTERNAL-VAL
          IDEXTERNAL
          MEASHIST-VAL
          MEASHIST
          BIRTHSTAMP-VAL
          BIRTHSTAMP
          BOBJECTVALID-VAL
          BOBJECTVALID
          BOBJECTNEW-VAL
          BOBJECTNEW
          BOBJECTMEASURED-VAL
          BOBJECTMEASURED
))