(cl:in-package definitions-msg)
(cl:export '(HEADER_PROTOCOLVERSION-VAL
          HEADER_PROTOCOLVERSION
          HEADER_MESSAGEID-VAL
          HEADER_MESSAGEID
          HEADER_STATIONID-VAL
          HEADER_STATIONID
          CAM_GENERATIONDELTATIME-VAL
          CAM_GENERATIONDELTATIME
          BASIC_CONTAINER-VAL
          BASIC_CONTAINER
          HIGH_FREQ_CONTAINER-VAL
          HIGH_FREQ_CONTAINER
          LOW_FREQ_CONTAINER-VAL
          LOW_FREQ_CONTAINER
          SPECIAL_CONTAINER-VAL
          SPECIAL_CONTAINER
))