(cl:in-package definitions-msg)
(cl:export '(PROTECTEDZONETYPE-VAL
          PROTECTEDZONETYPE
          EXPIRYTIMEPRESENT-VAL
          EXPIRYTIMEPRESENT
          EXPIRYTIME-VAL
          EXPIRYTIME
          PROTECTEDZONELATITUDE-VAL
          PROTECTEDZONELATITUDE
          PROTECTEDZONELONGITUDE-VAL
          PROTECTEDZONELONGITUDE
          PROTECTEDZONERADIUSPRESENT-VAL
          PROTECTEDZONERADIUSPRESENT
          PROTECTEDZONERADIUS-VAL
          PROTECTEDZONERADIUS
          PROTECTEDZONEID-VAL
          PROTECTEDZONEID
          PROTECTEDZONEIDPRESENT-VAL
          PROTECTEDZONEIDPRESENT
))