(cl:in-package definitions-msg)
(cl:export '(CONNECTIONID-VAL
          CONNECTIONID
          QUEUELENGTH-VAL
          QUEUELENGTH
          QUEUELENGTH_PRESENT-VAL
          QUEUELENGTH_PRESENT
          AVAILABLESTORAGELENGTH-VAL
          AVAILABLESTORAGELENGTH
          AVAILABLESTORAGELENGTH_PRESENT-VAL
          AVAILABLESTORAGELENGTH_PRESENT
          WAITONSTOP-VAL
          WAITONSTOP
          WAITONSTOP_PRESENT-VAL
          WAITONSTOP_PRESENT
          PEDBICYCLEDETECT-VAL
          PEDBICYCLEDETECT
          PEDBICYCLEDETECT_PRESENT-VAL
          PEDBICYCLEDETECT_PRESENT
          REGIONAL_VEHICLETOLANEPOSITIONS-VAL
          REGIONAL_VEHICLETOLANEPOSITIONS
          REGIONAL_RSUDISTANCEFROMANCHOR_CHOICE-VAL
          REGIONAL_RSUDISTANCEFROMANCHOR_CHOICE
          REGIONAL_RSUDISTANCEFROMANCHOR_NODE_X_LAT-VAL
          REGIONAL_RSUDISTANCEFROMANCHOR_NODE_X_LAT
          REGIONAL_RSUDISTANCEFROMANCHOR_NODE_Y_LON-VAL
          REGIONAL_RSUDISTANCEFROMANCHOR_NODE_Y_LON
))