(cl:in-package definitions-msg)
(cl:export '(MOVEMENTNAME-VAL
          MOVEMENTNAME
          MOVEMENTNAME_PRESENT-VAL
          MOVEMENTNAME_PRESENT
          SIGNALGROUP-VAL
          SIGNALGROUP
          STATE_TIME_SPEED-VAL
          STATE_TIME_SPEED
          MANEUVERASSISTLIST-VAL
          MANEUVERASSISTLIST
          MANEUVERASSISTLIST_PRESENT-VAL
          MANEUVERASSISTLIST_PRESENT
))