# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget InvertedPendulumActDynLinearizedForward HyALinearizedForward HyAJacInverseDynamicsReverse quadrotorDynamics hya_ik irb4600_ik ct_models HyQLinearizationCodegen InvertedPendulumWithActuatorCodeGen HyALinearizationCodegen)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target InvertedPendulumActDynLinearizedForward
add_library(InvertedPendulumActDynLinearizedForward STATIC IMPORTED)

set_target_properties(InvertedPendulumActDynLinearizedForward PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ct_rbd"
)

# Create imported target HyALinearizedForward
add_library(HyALinearizedForward STATIC IMPORTED)

set_target_properties(HyALinearizedForward PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ct_rbd"
)

# Create imported target HyAJacInverseDynamicsReverse
add_library(HyAJacInverseDynamicsReverse STATIC IMPORTED)

set_target_properties(HyAJacInverseDynamicsReverse PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ct_rbd"
)

# Create imported target quadrotorDynamics
add_library(quadrotorDynamics STATIC IMPORTED)

set_target_properties(quadrotorDynamics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ct_core"
)

# Create imported target hya_ik
add_library(hya_ik STATIC IMPORTED)

set_target_properties(hya_ik PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ct_rbd"
)

# Create imported target irb4600_ik
add_library(irb4600_ik STATIC IMPORTED)

set_target_properties(irb4600_ik PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ct_rbd"
)

# Create imported target ct_models
add_library(ct_models INTERFACE IMPORTED)

set_target_properties(ct_models PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ct_rbd;InvertedPendulumActDynLinearizedForward;HyALinearizedForward;HyAJacInverseDynamicsReverse;quadrotorDynamics;hya_ik;irb4600_ik"
)

# Create imported target HyQLinearizationCodegen
add_executable(HyQLinearizationCodegen IMPORTED)

set_target_properties(HyQLinearizationCodegen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
)

# Create imported target InvertedPendulumWithActuatorCodeGen
add_executable(InvertedPendulumWithActuatorCodeGen IMPORTED)

set_target_properties(InvertedPendulumWithActuatorCodeGen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
)

# Create imported target HyALinearizationCodegen
add_executable(HyALinearizationCodegen IMPORTED)

set_target_properties(HyALinearizationCodegen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rosuser/ws/catkin_workspace/src/dependencies/kindr/include;/usr/include/eigen3;/usr/local/include;/usr/local/include;/usr/include/eigen3;/home/rosuser/ws/catkin_workspace/devel/include;/opt/blasfeo/include;/opt/hpipm/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include;/home/rosuser/ws/catkin_workspace/devel/include/ct;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd;/home/rosuser/ws/catkin_workspace/devel/include/ct/rbd/robot/kinematics/ikfast;${_IMPORT_PREFIX}/include"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/ct_models_export-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
